



# Generated by Django 5.2.1 on 2025-05-30 20:40

from django.db import migrations, models

# This creates the initial database table for documents
class Migration(migrations.Migration):

    initial = True  # This is the first migration

    dependencies = [
    ]  # No dependencies since it's the first migration

    operations = [
        # Creates the Document model table in database
        migrations.CreateModel(
            name='Document',
            fields=[
                # Auto-incrementing primary key
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Document title field (max 255 characters)
                ('title', models.CharField(max_length=255)),
                # File upload field (saves to 'documents/' folder)
                ('file', models.FileField(upload_to='documents/')),
                # Stores file size in bytes
                ('file_size', models.IntegerField()),
                # Stores file extension (pdf, docx, etc.)
                ('file_type', models.CharField(max_length=10)),
                # Number of pages (defaults to 0)
                ('page_count', models.IntegerField(default=0)),
                # Processing status (Pending, Completed, Failed)
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=1)),
                # Auto-set to when document was uploaded
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]